-- ETH Cali site content seed — GENERATED, do not edit by hand.
--
-- Source: ethcaliorg/databases/*.csv and ethcaliorg/events/manifest.json
-- Regenerate: node scripts/build-content-seed.mjs
-- Apply:      psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f supabase/seed/site_content_seed.sql
--
-- Idempotent: parents conflict on slug, children on their (event_id, ...) unique
-- constraint. Verified by applying this file twice and comparing row counts.
-- Slugs are permanent public identifiers. Once this has run against production,
-- changing slugify() and regenerating would orphan every shared link — correct a
-- slug in the CMS instead.

begin;

insert into public.venues (slug, name, kind, status, maps_url, lat, lng) values
  ('binaural', 'Binaural', 'GastroBar', 'active', 'https://maps.app.goo.gl/oRua2cYx5jzkt7bk6', '3.450686', '-76.544001'),
  ('albahaca-terraza', 'Albahaca Terraza', 'GastroBar', 'active', 'https://maps.app.goo.gl/X2BAQxsmdaZxdcrd6', '3.454630', '-76.525842'),
  ('la-pergola', 'La Pergola', 'GastroBar', 'inactive', 'https://maps.app.goo.gl/JfDhKGyZ9jHjgWoW8', '3.454622', '-76.531496'),
  ('bengala-bandolero', 'Bengala Bandolero', 'Club Music', 'inactive', 'https://maps.app.goo.gl/Fh8gYrTUwJZ3ZdDQ7', '3.435016', '-76.541801'),
  ('discoteca-1060', 'Discoteca 1060', 'Club Music', 'active', 'https://maps.app.goo.gl/AaDxC247DFEue3kh9', '3.446899', '-76.532015'),
  ('colectivo-coworking', 'Colectivo Coworking', 'Coworking', 'active', 'https://maps.app.goo.gl/WaXtVbq51WyYJwxo8', '3.411830', '-76.539123'),
  ('ramada-cafe', 'RAMADA CAFE', 'Coworking', 'active', 'https://maps.app.goo.gl/4R99Qru9UKBzWpGr8', '3.376856', '-76.545655'),
  ('universidad-usb-laboratorio-financiero', 'Universidad USB - Laboratorio Financiero', 'University', 'active', null, null, null),
  ('universidad-icesi-laboratorio-financiero', 'Universidad ICESI -  Laboratorio Financiero', 'University', 'active', 'https://maps.app.goo.gl/ToW59gW56w4TxwoeA', '3.341895', '-76.530602'),
  ('universidad-uao', 'Universidad UAO', 'University', 'active', 'https://maps.app.goo.gl/djcuzzJCp375FqnMA', '3.353653', '-76.522986'),
  ('universidad-santiago-de-cali-usc', 'Universidad Santiago de Cali (USC)', 'University', 'active', 'https://maps.app.goo.gl/3hH8vgLzbJYxpjF2A', '3.403396', '-76.547065'),
  ('universidad-del-valle', 'Universidad del Valle', 'University', 'active', 'https://maps.app.goo.gl/ZyYV65dG2MrarX777', '3.431567', '-76.546745'),
  ('la-pizzicleta', 'La Pizzicleta', 'Restaurant', 'active', 'https://maps.app.goo.gl/JZKcachS6L1zKzUJ6', '3.452534', '-76.534725'),
  ('el-pizzaron', 'El Pizzaron', 'Restaurant', 'active', 'https://maps.app.goo.gl/NCtDGHFeLfRgziw37', '3.453389', '-76.532994'),
  ('la-galeria-de-la-plaza', 'La galería de la Plaza', 'Restaurant', 'active', 'https://maps.app.goo.gl/39dY3XbwBvYFX8Wx7', '3.455141', '-76.535353'),
  ('tdt-novena', 'TDT Novena', 'Restaurant', 'active', null, null, null),
  ('zona-america-nido-distrito-de-innovacion', 'Zona america - NIDO: Distrito de Innovacion', 'Office Partner', 'active', 'https://maps.app.goo.gl/Mb1RVAhBoaWDVte96', '3.327976', '-76.521277'),
  ('torre-de-cali-piso-40', 'Torre de Cali Piso 40', 'Office Partner', 'active', 'https://maps.app.goo.gl/4RrNkT1dWUGvsovH9', '3.458398', '-76.528742')
on conflict (slug) do nothing;

insert into public.team_members (slug, name, role_es, role_en, status, since, image_path, linkedin_url, twitter_url, github_url, sort_order) values
  ('william-martinez', 'William Martinez', 'Founder, Economist, Project Manager', null, 'Founder', '2022-10-01', '/team/william.png', 'https://www.linkedin.com/in/williammartinez8/', 'https://twitter.com/0xwmb', 'https://github.com/wmb81321', 0),
  ('juan-urrea', 'Juan Urrea', 'Researcher, Web3 Hacker', null, 'Founder', '2022-10-01', '/team/Juanurrea.png', null, 'https://twitter.com/juan21179', null, 1),
  ('filadelfo-caicedo', 'Filadelfo Caicedo', 'Economist, Trader, Web3 Researcher', null, 'Core', '2023-10-01', '/team/filadelfo.png', 'https://www.linkedin.com/in/filadelfo-caicedo/', 'https://twitter.com/Filatrader', 'https://github.com/phill900', 2),
  ('maria-del-mar-borrero', 'Maria del Mar Borrero', 'Community Manager, Digital Marketing', null, 'Core', '2024-02-01', '/team/mariadelmar.png', 'https://www.linkedin.com/in/mariadelmarborrerog/', 'https://twitter.com/marimarketingw3', null, 3),
  ('jose-bailon', 'Jose Bailon', 'Back-end Developer', null, 'Core', '2023-08-01', '/team/juan jose bailon.png', 'https://linkedin.com/in/juan-bailon-ab3767192', null, 'https://github.com/juanbailon', 4),
  ('cristobal-valencia', 'Cristobal Valencia', 'Full Stack Developer', null, 'Contributor', '2025-04-01', '/team/cristobal.jpg', 'https://www.linkedin.com/in/cristobalvalenciaceron', 'https://x.com/DevCristobalvc', 'https://github.com/DevCristobalvc', 5),
  ('juan-david-burgos', 'Juan David Burgos', 'Lawyer', null, 'Contributor', '2025-05-01', '/team/juan david burgos.jpg', 'https://www.linkedin.com/in/juan-david-burgos-cantor-1603b3196/', 'https://x.com/JuanBK_ethcali', 'https://github.com/orgs/Ekinoxis-evm/people/juandavid883', 6),
  ('luis-waitoto', 'Luis Waitoto', 'Web2 dev in course + logistics coordinator', null, 'Volunteer', '2025-11-01', '/team/luiswaitoto.jpg', 'https://www.linkedin.com/in/luiswaitoto-/', null, null, 7),
  ('john-alex', 'John Alex', 'Web2 dev in course', null, 'Volunteer', '2025-11-01', '/team/jhonalex.jpg', 'https://www.linkedin.com/in/jhonnalexandertorrescastro/', null, 'https://github.com/orgs/Ekinoxis-evm/people/DevJhonnTorres', 8),
  ('camilo-ramirez', 'Camilo Ramirez', 'Fullstack developer', null, 'Volunteer', '2025-11-01', '/team/camiloramirez.png', 'https://www.linkedin.com/in/camilo-ram%C3%ADrez-villegas/', null, null, 9),
  ('susan-taborda', 'Susan Taborda', 'Web2 Dev in course', null, 'Volunteer', '2025-11-01', '/team/susantaborda.png', 'https://www.linkedin.com/in/susan-taborda/', 'https://x.com/tabordasusan', null, 10),
  ('miguel-bolanos', 'Miguel Bolanos', 'Front-end and UXUI dev', null, 'Volunteer', '2025-11-01', '/team/miguelbolanos.png', 'https://www.linkedin.com/in/mab015/', 'https://twitter.com/MAB015', 'https://github.com/MAB015/MAB015', 11),
  ('laura-castro', 'Laura Castro', 'Lawyer and Customer Success', null, 'Volunteer', '2025-11-01', '/team/lauracastro.jpg', 'https://www.linkedin.com/in/launacg', null, null, 12),
  ('camilo-sacanamboy', 'Camilo Sacanamboy', 'Founder, WEB3 Developer', null, 'Volunteer', '2023-01-01', '/team/camilosacanamboy.png', 'https://www.linkedin.com/in/camilosaka/', 'https://twitter.com/camilosaka', 'https://github.com/csacanam', 13),
  ('juan-esteban-sierra', 'Juan Esteban Sierra', 'Business Developer, NFT Strategy', null, 'Former Core', '2022-12-01', '/team/juan esteban sierra.png', 'https://www.linkedin.com/in/juanfteth/', 'https://twitter.com/juaNFT_ETH', null, 14),
  ('saeta-florez', 'Saeta Florez', 'DAO and Talent Manager', null, 'Former Core', '2025-05-01', '/team/saeta.png', 'https://www.linkedin.com/in/saeta7/', 'https://x.com/Hortelana_eth', null, 15),
  ('adriana-lucema', 'Adriana Lucema', 'Project Manager, Web3 Product Manager', null, 'Former Core', '2023-06-01', '/team/adriana_lucema.png', 'https://www.linkedin.com/in/adriana-lucema/', 'https://twitter.com/AdriLucema', null, 16),
  ('jose-luis-rivas', 'Jose Luis Rivas', 'Educador, Web3 Hacker', null, 'Former Core', '2023-01-01', '/team/joseluisrivas.png', 'https://www.linkedin.com/in/jlrivasv/', 'https://twitter.com/cointaigas', null, 17),
  ('andres-jimenez', 'Andres Jimenez', 'Founder', null, 'Former Core', '2022-10-01', '/team/andresjimenez.png', 'https://www.linkedin.com/in/andresfjimenez/', 'https://twitter.com/Andresjimenezv', null, 18),
  ('camilo-tobar', 'Camilo Tobar', 'Founder, Web3 Hacker', null, 'Former Core', '2022-10-01', '/team/camilotobar.png', 'https://www.linkedin.com/in/camilotobarn/', null, null, 19)
on conflict (slug) do nothing;

insert into public.events (slug, kind, role, scope, starts_on, ends_on, city, country, location_url, name_es, poster_path, luma_slug, registration_url, rsvp_count, social_url, recap_url, photos_url, drive_folder_url, youtube_url, is_published, venue_id) values
  ('devcon-vi', 'other', 'volunteering', 'local', '2022-11-14', null, 'Bogotá', 'Colombia', 'https://maps.app.goo.gl/psm34tA11wb5kh2V8', 'Devcon VI', '/events/2022%2011%2014%20Devcon%20VI.png', null, null, null, 'https://www.instagram.com/p/CiAXXShMJ1J/', null, 'https://drive.google.com/drive/folders/1BmKSrXFahzPjON5bOy3tvnqi6KuGrHRH', null, null, true, null),
  ('ethereum-cali-opening', 'meetup', 'host', 'local', '2022-12-26', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/ojibHKVdbmaRtACy6', 'Ethereum cali Opening', null, null, null, 4, 'https://www.instagram.com/p/CmxVlz6J9Go/', 'https://www.instagram.com/p/CmxVlz6J9Go/', 'https://drive.google.com/drive/u/0/folders/1y4zf8_4sLS4SphWXRcoGVN6b86u9gIDI', null, null, true, (select id from public.venues where slug = 'discoteca-1060')),
  ('ethereans-del-pacifico-1', 'meetup', 'host', 'local', '2023-02-24', null, 'Cali', 'Colombia', 'https://g.co/kgs/12YiNw5', 'Ethereans del Pacifico 1', '/events/2023%2002%2023%20Ethereans%20del%20Pacifico.png', null, 'https://www.meetup.com/ethereumcali/events/291777540/?utm_medium=referral&utm_campaign=share-btn_savedevents_share_modal&utm_source=link&utm_version=v2', 3, 'https://www.instagram.com/p/CpDRcE6uuGz/', 'https://www.instagram.com/p/CpFyW8iOJzm/?img_index=1', 'https://drive.google.com/drive/u/0/folders/1ttr-X9LXeOuObiJpKiq9AF0bNSCStZ-9', null, null, true, null),
  ('revolucion-de-la-contabilidad-con-ai', 'conference', 'colab', 'local', '2023-03-01', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/B9XfBb4fCDLPVjhY7', 'Revolucion de la contabilidad con AI', '/events/2023%2003%2001%20Revolucion%20de%20la%20Contabilidad.png', null, 'https://www.meetup.com/ethereumcali/events/291777701/?utm_medium=referral&utm_campaign=share-btn_savedevents_share_modal&utm_source=link&utm_version=v2', 20, 'https://www.instagram.com/p/CpPzoeWub9s/', 'https://www.instagram.com/p/CpQshRxpO7E/?img_index=1', 'https://drive.google.com/drive/u/0/folders/1ZgTGr38xus-M3QwHHoV8O0BdRHdNkoup', null, null, true, (select id from public.venues where slug = 'universidad-santiago-de-cali-usc')),
  ('reinvencion-del-contador-en-el-siglo-xxi', 'conference', 'colab', 'local', '2023-03-01', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/Mta4fT2oWqxUynwq6', 'reinvencion del contador en el siglo xxi', '/events/2023%2003%2001%20Reinvencion%20del%20Contador.png', null, 'https://www.meetup.com/ethereumcali/events/291954715/?utm_medium=referral&utm_campaign=share-btn_savedevents_share_modal&utm_source=link&utm_version=v2', 20, 'https://www.instagram.com/p/CpPzoeWub9s/', 'https://www.instagram.com/p/CpRdGL8tELV/?img_index=1', 'https://drive.google.com/drive/folders/1HNQNOLOtTwn3tQYRqM9uJ5yBgvCncIIm?usp=drive_link', null, null, true, (select id from public.venues where slug = 'universidad-del-valle')),
  ('ethereum-at-the-river', 'meetup', 'host', 'local', '2023-03-11', null, 'Cali', 'Colombia', 'https://g.co/kgs/12YiNw5', 'Ethereum at the River', '/events/2023%2003%2011%20Ethereum%20at%20the%20River.png', null, 'https://www.meetup.com/ethereumcali/events/292144032/?utm_medium=referral&utm_campaign=share-btn_savedevents_share_modal&utm_source=link&utm_version=v2', 7, 'https://www.instagram.com/p/CpqXsCsvkI4/', 'https://www.instagram.com/p/CpsbmR2OxBA/', 'https://drive.google.com/drive/folders/1LK8exLe9biQMs76NzaxUh-LNf5ZMhdMW?usp=drive_link', null, null, true, null),
  ('ethereans-del-pacifico-2', 'meetup', 'host', 'local', '2023-04-29', null, 'Cali', 'Colombia', 'https://g.co/kgs/12YiNw5', 'Ethereans del pacifico 2', '/events/2023%2004%2029%20Ethereans%20del%20Pacifico%202%201000x1000.png', null, 'https://www.meetup.com/ethereumcali/events/293164121/?utm_medium=referral&utm_campaign=share-btn_savedevents_share_modal&utm_source=link&utm_version=v2', 10, 'https://www.instagram.com/p/CrjHfJepYlD/', 'https://www.instagram.com/p/Crq4mEzJYx7/?img_index=1', 'https://drive.google.com/drive/u/0/folders/1I3lggk-xAUCt8edKJP-JiRbR6pT458Km', null, null, true, null),
  ('workshop-digital-art-colombia-en-cali-medellin-y-bogota', 'workshop', 'colab', 'local', '2023-05-19', null, null, 'Colombia', 'https://maps.app.goo.gl/z8w3fojn2rn3mHnR9', 'Workshop: Digital Art Colombia en Cali, Medellin y Bogota.', '/events/2023%2005%2019%20workshop%20digital%20art.png', null, 'https://www.meetup.com/es-ES/ethereumcali/events/293777059/?eventOrigin=group_events_list', 10, 'https://www.instagram.com/p/Cs46atlNXMu/?next=%2Freel%2FDJuBYZFuOPX%2F', 'https://www.instagram.com/p/CtUdP_Hp7Dt/?next=%2Freel%2FDJuBYZFuOPX%2F&img_index=1', 'https://drive.google.com/drive/u/0/folders/1JR1kEX37AnLrVarkW1BplZaYZhVsLpwj', null, 'https://www.youtube.com/live/6GyG8ifcTkw?si=MJy9MMv9KeTOtxvg', true, null),
  ('global-pizza-party-2023', 'meetup', 'colab', 'local', '2023-05-22', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/FzvEwz9wSMGn2Yqn6', 'Global Pizza Party 2023', '/events/2023%2005%2022%20Global%20Pizza%20Party%202023.png', null, null, 20, 'https://www.instagram.com/p/Cs2O02urc0x/?next=%2Freel%2FDJuBYZFuOPX%2F', 'https://www.instagram.com/p/Cs2O02urc0x/', 'https://drive.google.com/drive/u/0/folders/1WoPtiO1Q9e1ATqhvYWKze3RO-S23vdGO', null, null, true, (select id from public.venues where slug = 'la-pizzicleta')),
  ('hashfest-2023', 'other', 'volunteering', 'local', '2023-07-27', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/RKPRbjs8vf3QHWoP7', 'Hashfest 2023', '/events/2023%2007%2027%20Hashfest.png', null, null, 50, 'https://www.instagram.com/hashfest/', 'https://www.instagram.com/hashfest/', 'https://drive.google.com/drive/u/0/folders/1PxK-fEF9YMYiNK-m_iZumThhLpCR-SEO', null, null, true, null),
  ('ethereum-birthday-2023-empresarios-web3', 'meetup', 'host', 'local', '2023-08-16', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/2kNFWM883z1jCdez7', 'Ethereum Birthday 2023 - Empresarios Web3', '/events/2023%2008%2016%20Ethereum%20Birthday%202023%20-%20Empresarios%20Web3%20%20.png', null, 'https://www.meetup.com/es-ES/ethereumcali/events/294439100/?eventOrigin=group_events_list', 29, 'https://www.instagram.com/p/Cv_LFbMN56U/?img_index=1', 'https://www.instagram.com/p/CwjPLlLtHcc/?img_index=1', 'https://drive.google.com/drive/folders/1Xp-6K9BIIDpNFhnsmW2iEt3zYqxpKDkj?usp=drive_link', null, 'https://youtu.be/cqtfKeaYViM?si=uxbdhvzNl_QO1Z_g', true, (select id from public.venues where slug = 'colectivo-coworking')),
  ('workshop-set-up-en-evm-una-wallet-un-token-y-un-nft', 'workshop', 'colab', 'local', '2023-08-19', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/7hfQyZcaDXTnKk7w5', 'Workshop: Set-up en EVM: Una Wallet, un Token y un NFT', '/events/2023%2008%2019%20Workshop%3A%20Set-up%20en%20EVM%3A%20Una%20Wallet%2C%20un%20Token%20y%20un%20NFT.png', null, 'https://www.meetup.com/es-ES/ethereumcali/events/295522958/?eventOrigin=group_events_list', 10, 'https://www.instagram.com/p/CwFzAKruQIb/', 'https://www.instagram.com/p/Cwz6uP9u8kS/?img_index=1', 'https://drive.google.com/drive/folders/1mNqcbF0m0JRf0v1DD9REzj-k3u4J3FjQ?usp=drive_link', null, null, true, null),
  ('ethereum-starter-pack-billeteras-blockchain-self-custodial', 'workshop', 'colab', 'local', '2023-08-24', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/fSBzBAzGZXsGWB1S8', 'Ethereum Starter Pack - Billeteras Blockchain Self-Custodial', '/events/2023%2008%2024%20a%2010%2023%20Ethereum%20Starter%20Pack%20.png', null, 'https://www.meetup.com/ethereumcali/events/295624050/?utm_medium=referral&utm_campaign=share-btn_savedevents_share_modal&utm_source=link&utm_version=v2', 10, 'https://www.instagram.com/p/CwRXIWKNtgu/', 'https://www.instagram.com/p/CxE1GWYtX8p/?img_index=1', null, null, null, true, (select id from public.venues where slug = 'universidad-icesi-laboratorio-financiero')),
  ('ethereum-starter-pack-blockchain-y-web3', 'workshop', 'colab', 'local', '2023-08-31', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/fSBzBAzGZXsGWB1S8', 'Ethereum Starter Pack - Blockchain y WEB3', null, null, 'https://www.meetup.com/ethereumcali/events/295750565/?utm_medium=referral&utm_campaign=share-btn_savedevents_share_modal&utm_source=link&utm_version=v2', 4, 'https://www.instagram.com/p/CwlyZgkNdEh/', null, null, null, null, true, (select id from public.venues where slug = 'universidad-icesi-laboratorio-financiero')),
  ('ethereum-starter-pack-ethereum-101', 'workshop', 'colab', 'local', '2023-09-07', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/fSBzBAzGZXsGWB1S8', 'Ethereum Starter Pack  - Ethereum 101', null, null, 'https://www.meetup.com/ethereumcali/events/295897367/?utm_medium=referral&utm_campaign=share-btn_savedevents_share_modal&utm_source=link&utm_version=v2', 4, 'https://www.instagram.com/p/Cwyt0XmNTCL/', null, null, null, null, true, (select id from public.venues where slug = 'universidad-icesi-laboratorio-financiero')),
  ('ethereum-starter-pack-defi', 'workshop', 'colab', 'local', '2023-09-14', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/fSBzBAzGZXsGWB1S8', 'Ethereum Starter Pack - Defi', null, null, 'https://app.unlock-protocol.com/event/ethereum-starter-pack-n-4', 3, null, null, null, null, null, true, (select id from public.venues where slug = 'universidad-icesi-laboratorio-financiero')),
  ('capital-summit-2023', 'other', 'participant', 'local', '2023-09-18', null, 'Cali', 'Colombia', 'https://valledelpacifico.co/en/valle-del-pacifico-event-center/', 'Capital Summit 2023', null, null, null, null, 'https://www.instagram.com/p/CuZ5rD0OxUQ/', 'https://www.instagram.com/p/CxVgKcAuGJy/?img_index=1', 'https://drive.google.com/drive/folders/1Q0kHT-m4MdOK_aouIHYOAXc6h4bJ1ibj?usp=drive_link', null, null, true, null),
  ('ethereum-starter-pack-nft-101', 'workshop', 'colab', 'local', '2023-09-21', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/fSBzBAzGZXsGWB1S8', 'Ethereum Starter Pack - NFT 101', null, null, 'https://app.unlock-protocol.com/event/ethereum-starter-pack-4-nft-101-icesi', 3, null, null, null, null, null, true, (select id from public.venues where slug = 'universidad-icesi-laboratorio-financiero')),
  ('ethereum-starter-pack-seguridad-en-web3', 'workshop', 'colab', 'local', '2023-10-12', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/fSBzBAzGZXsGWB1S8', 'Ethereum Starter Pack - Seguridad en WEB3', null, null, 'https://app.unlock-protocol.com/event/ethereum-starter-pack-7-seguridad-web-3-101-icesi', 3, null, null, null, null, null, true, (select id from public.venues where slug = 'universidad-icesi-laboratorio-financiero')),
  ('blockchain-summit-latam-2023', 'other', 'volunteering', 'local', '2023-10-04', null, 'Bogotá', 'Colombia', 'https://maps.app.goo.gl/psm34tA11wb5kh2V8', 'Blockchain Summit Latam 2023', null, null, null, null, 'https://www.instagram.com/p/CxG5TrWpR_1/', 'https://www.instagram.com/p/CyRijBGpPP5/?img_index=1', 'https://drive.google.com/drive/folders/17iX2hJCAIvLL0u3Q1G2QlTjqYZqzXoPW?usp=drive_link', null, null, true, null),
  ('ethcolombia-day', 'meetup', 'cohost', 'local', '2023-10-07', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/xnr5X1thAj8m9XQa8', 'ETHColombia Day', '/events/2023%2010%207%20ETHColombia%20Day.png', null, 'https://www.meetup.com/es-ES/ethereum-bogota/events/296389656/?eventOrigin=group_events_list', 50, 'https://www.instagram.com/p/CyRn6mzpgDm/', 'https://www.instagram.com/p/CyRrv2RJ5Ai/?img_index=1', 'https://drive.google.com/drive/folders/1GkTPxY39osjIKKENtl6Eq4ev4wugoPFO?usp=drive_link', null, null, true, null),
  ('python-day-cali', 'other', 'participant', 'local', '2023-10-23', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/oZjghE9Z3Zsk6i9H8', 'Python Day Cali', '/events/2023%2010%2023%20Pyday%20Cali.png', null, null, null, 'https://www.instagram.com/p/CxQ6VF8P8qW/', 'https://www.instagram.com/p/CzHoOyeJYkJ/?img_index=1', 'https://drive.google.com/drive/folders/1eRelSivzYXTEilop8_wH-ELQ7BfFcqIL?usp=drive_link', null, null, true, (select id from public.venues where slug = 'universidad-uao')),
  ('data-day-uao', 'conference', 'host', 'local', '2023-11-03', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/oZjghE9Z3Zsk6i9H8', 'Data DAY UAO', '/events/2023%2011%2003%20Data%20Day%20UAO.png', null, null, null, 'https://www.instagram.com/p/CzG11AwulFX/', null, 'https://drive.google.com/drive/u/0/folders/14h0toD0bKKLctzMYAywn-R0H2N_B7g3l', null, null, true, (select id from public.venues where slug = 'universidad-uao')),
  ('ramada-cafe-opening', 'meetup', 'colab', 'local', '2023-11-04', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/RCNYuJLKH1kLJo5TA', 'Ramada Cafe Opening', '/events/2023%2011%2004%20Ramada%20Cafe%20Opening.png', null, 'https://app.unlock-protocol.com/event/inauguracion-ramada-cafe-cripto-cafe', 15, null, 'https://www.instagram.com/p/Czg86JCgC67/?img_index=1', 'https://drive.google.com/drive/u/0/folders/1xlhB1tegcO7aDgvaM9PrQfl0DetN2oRH', null, null, true, (select id from public.venues where slug = 'ramada-cafe')),
  ('taller-programacion-de-contratos-inteligentes-con-solidity-icesi', 'workshop', 'colab', 'local', '2023-11-18', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/fSBzBAzGZXsGWB1S8', 'Taller Programación de Contratos Inteligentes con Solidity - ICESI', '/events/2023%2011%2018%20Taller%20Programacion%20Solidity.png', null, 'https://app.unlock-protocol.com/event/taller-programacion-de-contratos-inteligentes-icesi', 20, null, 'https://www.instagram.com/p/Cz16mJrA9Jx/?img_index=3', 'https://drive.google.com/drive/u/0/folders/1cGrpV8CnGFqD9lNUoKfwePD4TODS_-2d', null, null, true, (select id from public.venues where slug = 'universidad-icesi-laboratorio-financiero')),
  ('proof-of-stake-en-ramada-cafe', 'meetup', 'host', 'local', '2023-12-16', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/RCNYuJLKH1kLJo5TA', 'Proof-of-Stake en Ramada Cafe', '/events/2023%2012%2016%20Proof-of-Stake%20en%20Ramada%20Cafe.png', null, 'https://app.unlock-protocol.com/event/proof-of-stake', 7, 'https://www.instagram.com/p/C05AkIGujWE/?img_index=1', 'https://x.com/ethereum_cali/status/1736768163197370438', 'https://drive.google.com/drive/folders/1nIhSDzVMgAdJktLPDtEXceaXf59a8c5n?usp=drive_link', null, null, true, (select id from public.venues where slug = 'ramada-cafe')),
  ('hackathon-web3-ethcolombia', 'hackathon', 'cohost', 'local', '2023-11-27', null, 'Cali', 'Colombia', 'https://www.instagram.com/ramadacafeco/', 'Hackathon WEB3 Ethcolombia', '/events/2023%2011%2027%20Hackathon%20WEB3%20Ethcolombia.png', null, null, null, 'https://www.instagram.com/p/C0MsMz6g4So/?img_index=1', 'https://www.instagram.com/p/C0wee_lssGZ/?img_index=1', 'https://drive.google.com/drive/u/5/folders/1sRj-6rS-5fdaLZxASRXSgu8c68uFDQCT', null, null, true, (select id from public.venues where slug = 'ramada-cafe')),
  ('qf-ethcolombia-meetup-cali', 'meetup', 'host', 'local', '2024-03-09', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/7uNBMMA1QKg2d8EC8', 'QF ETHColombia Meetup Cali', '/events/2024%2003%2024%20QF%20ETHColombia%20Meetup%20Cali.png', null, 'https://www.meetup.com/ethereumcali/events/299455403/?loginProvider=google', 17, 'https://www.instagram.com/p/C4OIs15uahf/?img_index=1', 'https://www.instagram.com/p/C4izdNOAX91/', 'https://drive.google.com/drive/folders/10ESbRUvHUkHIpsYIDTRXttsn4RMUlEtx?usp=drive_link', null, null, true, (select id from public.venues where slug = 'torre-de-cali-piso-40')),
  ('road-to-drumcode-global-pizza-party-2024', 'meetup', 'colab', 'local', '2024-05-22', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/ptjQG1A1RoE6TmHX8', 'Road to Drumcode: Global Pizza Party 2024', '/events/2024%2005%2022%20Road%20to%20Drumcode_%20Global%20Pizza%20Party%202024.png', null, null, 20, 'https://www.instagram.com/p/C7P64PON19F/', 'https://x.com/ethereum_cali/status/1793828622479819116', 'https://drive.google.com/drive/folders/1uhaSbg878q2B21_F3YUkhQVM61vjE9md?usp=drive_link', null, null, true, (select id from public.venues where slug = 'albahaca-terraza')),
  ('road-to-drumcode-discoteca-1060', 'meetup', 'colab', 'local', '2024-05-25', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/ojibHKVdbmaRtACy6', 'Road to Drumcode: Discoteca 1060', '/events/2024%2005%2025%20%20Road%20to%20Drumcode_%20Discoteca%201060.png', null, 'https://app.unlock-protocol.com/event/drumcode-discoteca-1060-1', 12, 'https://www.instagram.com/p/C7XKBCoAbJI/', 'https://www.instagram.com/p/C7cueOyMYb7/', 'https://drive.google.com/drive/folders/1-gktBqr3xVHhPA2owdxa2bhoiShYwErq', null, null, true, (select id from public.venues where slug = 'discoteca-1060')),
  ('road-to-drumcode-pizzicleta', 'meetup', 'colab', 'local', '2024-06-01', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/FzvEwz9wSMGn2Yqn6', 'Road to Drumcode: Pizzicleta', null, null, null, 10, 'https://www.instagram.com/p/C7mPwePsFNI/', 'https://www.instagram.com/p/C7zag1hvZ_e/', 'https://drive.google.com/drive/folders/1-kl5ktJkycK99l0vg6LRaWYupx-nbou9?usp=drive_link', null, null, true, (select id from public.venues where slug = 'la-pizzicleta')),
  ('drumcode-cali', 'other', 'colab', 'local', '2024-06-21', null, 'Cali', 'Colombia', 'https://valledelpacifico.co/en/valle-del-pacifico-event-center/', 'Drumcode Cali', '/events/2024%2006%2021%20Drumcode%20Cali.jpeg', null, 'https://valledelpacifico.co/events/concierto-electronico-drumcode/', null, 'https://www.instagram.com/p/C7zag1hvZ_e/', 'https://www.instagram.com/p/C7cueOyMYb7/', 'https://drive.google.com/drive/folders/1W7Dq27f7zTipRjtke9A1Z999SDIwim6d?usp=drive_link', null, null, true, null),
  ('base-community-meetup-1-ethereum-birthday-2024', 'meetup', 'host', 'local', '2024-07-28', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/ZNouZAVnR6huCYgM7', 'BASE Community Meetup #1 + Ethereum Birthday 2024', '/events/2024%2007%2028%20BASE%20Community%20Meetup%20%231%20%2B%20Ethereum%20Birthday%202024.png', 'b8xns9iz', 'https://lu.ma/b8xns9iz', 33, 'https://www.instagram.com/p/C-AtSHGAxis/', 'https://x.com/ethereum_cali/status/1817944044107940245', 'https://drive.google.com/drive/u/0/folders/1idJB18whEHiZ4w3Av6ciTwQvI-ADsWVn', null, null, true, (select id from public.venues where slug = 'binaural')),
  ('financiando-tus-bienes-publicos-con-giveth', 'workshop', 'colab', 'local', '2024-09-20', null, null, null, 'https://happ3n.xyz/listing/financiando-tus-bienes-publicos-con-giveth/', 'Financiando tus bienes publicos con Giveth', '/events/2024%2009%2020%20Financiando%20tus%20bienes%20publicos%20con%20Giveth.png', null, null, 53, 'https://x.com/ethereum_cali/status/1836134002320924993', 'https://x.com/ethereum_cali/status/1837170007458918652', 'https://drive.google.com/drive/u/0/folders/1ZTmKTFLIkzGYkG4Y9ifGKi_dPEbNeJjs', null, null, true, null),
  ('devcon-vii-thailandia', 'other', 'volunteering', 'international', '2024-11-11', null, 'Bangkok', 'Tailandia', 'https://maps.app.goo.gl/RUYsjPSQ4tHPGhz36', 'Devcon VII Thailandia', '/events/2024%2011%2014%20Devcon%20VII%20Thailandia.png', null, null, null, null, 'https://x.com/ethereum_cali/status/1856207604307112113', 'https://drive.google.com/drive/u/5/folders/1DqgUWFqp249w4SqCjdXmcdFfJhZD92Pa', null, null, true, null),
  ('base-community-meetup-2-onchain-education-with-icesi', 'workshop', 'host', 'local', '2024-11-12', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/fSBzBAzGZXsGWB1S8', 'Base Community Meetup #2: Onchain Education with ICESI', '/events/2024%2011%2012%20Base%20Community%20Meetup%20%232_%20Onchain%20Education%20with%20ICESI.png', 'kil2sxsa', 'https://lu.ma/kil2sxsa', 24, 'https://farcaster.xyz/filadelfo/0x665b1843', 'https://x.com/ethereum_cali/status/1856207604307112113', 'https://drive.google.com/drive/u/5/folders/10IYh7mZY8EQbcb43CO2Z9Ue1ANAEJmpS', null, null, true, (select id from public.venues where slug = 'universidad-icesi-laboratorio-financiero')),
  ('base-community-meetup-3-build-digital-portfolios-with-defi-ethereum', 'workshop', 'host', 'local', '2025-03-06', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/fSBzBAzGZXsGWB1S8', 'Base Community Meetup #3: Build Digital Portfolios with DeFi & Ethereum', '/events/2025%2005%2009%20Base%20Community%20Meetup%20%233_%20Build%20Digital%20Portfolios%20with%20DeFi%20%26%20Ethereum.png', 'gmx03hiy', 'https://lu.ma/gmx03hiy', 38, 'https://www.instagram.com/p/DHJGlA9stQ_/', 'https://x.com/ethereum_cali/status/1899697839933956144', 'https://drive.google.com/drive/u/5/folders/1cpZk7xQ7JxSjL6_M8fqzwUU8IJP9oAq9', null, null, true, (select id from public.venues where slug = 'universidad-icesi-laboratorio-financiero')),
  ('hacksession-base-batch-latam-zonamerica-colombia', 'hackathon', 'colab', 'local', '2025-05-09', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/TVrbvBFtNSAtXwmc8', 'Hacksession Base Batch LATAM: Zonamerica Colombia', '/events/2025%2005%2009%20Hacksession%20Base%20Batch%20LATAM_%20Zonamerica%20Colombia.png', '8waabg4p', 'https://lu.ma/8waabg4p', 18, 'https://www.instagram.com/p/DJUWDBNtKMd/', 'https://x.com/ethereum_cali/status/1921757100348199157', 'https://drive.google.com/drive/u/5/folders/1fIHEDtl17RvI5PbjL7evvdf66Kb4LZT0', null, null, true, (select id from public.venues where slug = 'zona-america-nido-distrito-de-innovacion')),
  ('open-house-usb', 'other', 'colab', 'local', '2025-05-17', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/LyMuBxNwh3ucryJU7', 'Open House USB', '/events/2025%2005%2017%20Open%20House%20USB.png', null, null, null, 'https://www.instagram.com/p/DJVNlUON3Q0/?img_index=1', 'https://x.com/ethereum_cali/status/1923851977596994032', 'https://drive.google.com/drive/u/5/folders/1zCCdhp0_zmE-ei14Xm5qB9qiVeRlx1lG', null, null, true, (select id from public.venues where slug = 'universidad-usb-laboratorio-financiero')),
  ('global-pizza-party-2025', 'meetup', 'colab', 'local', '2025-05-22', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/ptjQG1A1RoE6TmHX8', 'Global Pizza Party 2025', '/events/2025%2005%2022%20Global%20Pizza%20Party%202025.png', null, 'https://app.unlock-protocol.com/event/global-pizza-party-cali', 70, 'https://www.instagram.com/p/DJib9JetHWs/?img_index=1', 'https://x.com/ethereum_cali/status/1926393378444341576', 'https://drive.google.com/drive/u/5/folders/1wxH-HB2CiZ12M1aJpk9JW-DSQ2FdRAb9', null, null, true, (select id from public.venues where slug = 'albahaca-terraza')),
  ('papayogin', 'other', 'colab', 'local', '2025-06-08', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/v3zr3VpMmAF53oPc6', 'Papayogin', '/events/2025%2006%2008%20Papayogin.png', null, 'https://www.lapapaya.org/registrations.html', 100, 'https://www.instagram.com/p/DKxAt13MgNT/?img_index=1', 'https://x.com/ethereum_cali/status/1934763004903510431', 'https://drive.google.com/drive/u/0/folders/1tworC10KhfhWN01GOokqRlDjiIIBOeEG', null, null, true, null),
  ('hackathon-web3-cali', 'hackathon', 'colab', 'local', '2025-06-13', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/TVrbvBFtNSAtXwmc8', 'Hackathon WEB3 Cali', '/events/2025%2006%2013%20Hackathon%20WEB3%20Cali.png', 'fd6wh1ny', 'https://lu.ma/fd6wh1ny', 63, 'https://www.instagram.com/p/DLnzIuhyK4R/?img_index=3', 'https://x.com/ethereum_cali/status/1938020882028368119', 'https://drive.google.com/drive/u/5/folders/1fmLh91acj4v9CUEtzGPn-gFCxHudvLqw', null, null, true, (select id from public.venues where slug = 'zona-america-nido-distrito-de-innovacion')),
  ('hackathon-usc', 'hackathon', 'colab', 'local', '2025-07-19', null, 'Cali', 'Colombia', 'https://www.google.com/maps?sca_esv=656b10c93ec889a4&output=search&q=universidad+santiago+de+cali&source=lnms&fbs=AIIjpHx4nJjfGojPVHhEACUHPiMQ888Yp7kQAgn2suUAOWN4gr_S9GlBEYq0W4Xv3oU6cItbNYt_EA4ieM518BbxPk_13C3Iq0fG4vIbC5nrT71tiwngSc6BD4iYF9lWq2HkxIRqne67bU4bB4AhwuBuRp8ONH4Hwux-lsLZyIkNYarmIbMTEq3kKMsvoXkxcGWv9ZpQnIxOtq3PfswQLaRvo2je7pj23g&entry=mc&ved=1t:200715&ictx=111', 'Hackathon USC', '/events/2025%2007%2019%20Hackathon%20USC.png', null, null, null, 'https://www.instagram.com/p/DLkXR9Ei7pD/', 'https://x.com/ethereum_cali/status/1946696290424984051', 'https://drive.google.com/drive/u/5/folders/1Xa5vDvcQj_3CBTcMG6mfaA3OBSZB-x3k', null, null, true, (select id from public.venues where slug = 'universidad-santiago-de-cali-usc')),
  ('uniswap-on-the-ground', 'other', 'participant', 'local', '2025-07-28', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/tZo9Fuk4h1nBEYsaA', 'Uniswap On the Ground', '/events/2025%2007%2028%20Uniswap%20On%20the%20Ground.png', 'v4eotmg0', 'https://lu.ma/v4eotmg0', null, 'https://www.instagram.com/p/DMv9T8mMciP/?img_index=1', 'https://x.com/ethereum_cali/status/1949934492564484378', 'https://drive.google.com/drive/u/5/folders/1Cm9C48qDJTrhNul8M-N2tyQUid19bztg', null, null, true, null),
  ('destino-devconnect-la-sucursal-del-cielo-ethereum-birthday-2025-10y', 'meetup', 'host', 'local', '2025-08-09', null, 'Cali', 'Colombia', 'https://maps.app.goo.gl/TVrbvBFtNSAtXwmc8', 'Destino Devconnect - La Sucursal del Cielo + Ethereum Birthday 2025 10Y', '/events/2025%2008%2009%20Destino%20Devconnect%20-%20La%20Sucursal%20del%20Cielo%20%2B%20Ethereum%20Birthday%202025%2010Y.jpg', 'kl71zv1d', 'https://lu.ma/kl71zv1d', 62, 'https://www.instagram.com/p/DNQcUTbsB5e/?img_index=3', null, 'https://drive.google.com/drive/u/5/folders/1KPIrfm3-qi8krZnPAMVXgzlaAV94ZpWj', null, 'https://www.youtube.com/watch?v=rzQNoONVrIE', true, (select id from public.venues where slug = 'zona-america-nido-distrito-de-innovacion')),
  ('ehtereum-nyc-next-fin-research-forum', 'other', 'participant', 'international', '2025-08-11', null, 'Nueva York', 'Estados Unidos', 'https://maps.app.goo.gl/k1ZtPosmHh2E86927', 'Ehtereum NYC: Next Fin + Research Forum', '/events/2025%2008%2011%20ETHEREUM%20NYC%20next%20fin%20summit.avif', 'ozlqxrph', 'https://lu.ma/ozlqxrph?tk=F7vgaE', null, null, null, 'https://drive.google.com/drive/folders/1P5pBfYHE2PQ9Dh06IbItEjoO6o0AH5z7', null, null, true, null),
  ('cripto-latin-fest-2025', 'other', 'participant', 'local', '2025-08-21', null, 'Medellín', 'Colombia', 'https://maps.app.goo.gl/vGUxaQx7eERh47yNA', 'Cripto Latin Fest 2025', null, null, 'https://criptolatinfest.com/', null, null, null, 'https://drive.google.com/drive/folders/1DaBtL543CV3KtONghKb0jZ4EXcXxrHYw', null, null, true, null)
on conflict (slug) do nothing;

insert into public.event_poaps (event_id, poap_url, chain, collectors)
select e.id, v.poap_url, v.chain, v.collectors
from (values
  ('ethereum-cali-opening'::text, 'https://poap.gallery/drops/93758'::text, null::text, 0::integer),
  ('ethereum-birthday-2023-empresarios-web3', 'https://poap.gallery/drops/147806', 'Gnosis', 13),
  ('workshop-set-up-en-evm-una-wallet-un-token-y-un-nft', 'https://poap.gallery/drops/147944', 'Gnosis', 20),
  ('ethereum-starter-pack-defi', 'https://poap.gallery/drops/150009', 'Gnosis', 0),
  ('ethereum-starter-pack-nft-101', 'https://poap.gallery/drops/150539', 'Gnosis', 6),
  ('data-day-uao', 'https://poap.gallery/drops/157654', 'Gnosis', 3),
  ('ramada-cafe-opening', 'https://poap.gallery/drops/157665', 'Gnosis', 0),
  ('taller-programacion-de-contratos-inteligentes-con-solidity-icesi', 'https://poap.gallery/drops/159246', 'Gnosis', 16),
  ('destino-devconnect-la-sucursal-del-cielo-ethereum-birthday-2025-10y', 'https://poap.gallery/drops/195225', 'Base', null)
) as v(slug, poap_url, chain, collectors)
join public.events e on e.slug = v.slug
on conflict on constraint event_poaps_unique do nothing;

insert into public.event_nfts (event_id, protocol, nft_url, chain, mints)
select e.id, v.protocol, v.nft_url, v.chain, v.mints
from (values
  ('ethereum-cali-opening'::text, 'POAP'::text, null::text, null::text, null::integer),
  ('ethereum-birthday-2023-empresarios-web3', 'POAP', null, null, null),
  ('workshop-set-up-en-evm-una-wallet-un-token-y-un-nft', 'POAP', null, null, null),
  ('ethereum-starter-pack-ethereum-101', 'Unlock Protocol', 'https://polygonscan.com/address/0xadc3d1f73d2fa9aee898fae36c8d95a9d756b680', 'Polygon', 0),
  ('ethereum-starter-pack-defi', 'Unlock Protocol + POAP', 'https://polygonscan.com/token/0x70bd76e89478400d9ee4c0f1200e53e751610ecf', 'Polygon', 4),
  ('ethereum-starter-pack-nft-101', 'Unlock Protocol + POAP', 'https://polygonscan.com/token/0xD8b6092d2DB8E71eb7753d0F5Ad13B5C0cD59457', 'Polygon', 2),
  ('ethereum-starter-pack-seguridad-en-web3', 'Unlock Protocol', 'https://optimistic.etherscan.io/token/0xfcf03741a264a00fda35a5814e669968cab95204', 'Optimism', 4),
  ('data-day-uao', 'POAP', null, null, null),
  ('ramada-cafe-opening', 'Unlock Protocol + POAP', 'https://polygonscan.com/token/0xc67db733d754753ca19a3502f36756e9e4141cbd', 'Polygon', 15),
  ('taller-programacion-de-contratos-inteligentes-con-solidity-icesi', 'Unlock Protocol + POAP', 'https://polygonscan.com/token/0x2296e9d389a8c7dc2598d197e9fe43ea12052883', 'Polygon', 22),
  ('proof-of-stake-en-ramada-cafe', 'Unlock Protocol', 'https://optimistic.etherscan.io/token/0x9eb1dc77ac01b823f94c25ea054650930a3b7050', 'Optimism', 7),
  ('qf-ethcolombia-meetup-cali', 'Unlock Protocol', 'https://optimistic.etherscan.io/token/0xfc78b9ee7348d4184f85ba8a3a0350216ae950b0', 'Optimism', 1),
  ('road-to-drumcode-discoteca-1060', 'Unlock Protocol', 'https://basescan.org/token/0x8dB8003c692d68dD20722EDA6FC4de8708Cd5ED6', 'Base', 12),
  ('drumcode-cali', 'Unlock Protocol', 'https://basescan.org/address/0x1337722f177E99c8Cd490F432A319d8c7a003Ea8', 'Base', 39),
  ('base-community-meetup-1-ethereum-birthday-2024', 'Unlock Protocol', 'https://basescan.org/address/0x19f7b2834ca07ececefc21202714b3c667588aa9', 'Base', 76),
  ('financiando-tus-bienes-publicos-con-giveth', 'Unlock Protocol', 'https://optimistic.etherscan.io/token/0x62a2c557092eafe5c24151ed8e52ecaba6ac44a7', 'Optimism', 51),
  ('base-community-meetup-2-onchain-education-with-icesi', 'Unlock Protocol', 'https://basescan.org/address/0x19f7b2834ca07ececefc21202714b3c667588aa9', 'Base', 76),
  ('base-community-meetup-3-build-digital-portfolios-with-defi-ethereum', 'Unlock Protocol', 'https://basescan.org/address/0x19f7b2834ca07ececefc21202714b3c667588aa9', 'Base', 76),
  ('open-house-usb', 'Unlock Protocol', 'https://basescan.org/address/0x7082f47ca600240f41a2fbee26a894d875a63b2f', 'Base', 91),
  ('global-pizza-party-2025', null, 'https://basescan.org/token/0x95cDEA5535E8b601a4B588dF8F19bb02C618f0e1', 'Base', 70),
  ('papayogin', 'Unlock Protocol', 'https://optimistic.etherscan.io/token/0xce984f9e6335198fff193cc0596489dc9e570f3f', 'Optimism', 63),
  ('hackathon-web3-cali', 'Unlock Protocol', 'https://opensea.io/item/base/0x2744a0d99fc319c37d72ae9e98cba1b351bc37d5/2', 'Base', 42),
  ('hackathon-usc', 'Unlock Protocol', 'https://optimistic.etherscan.io/token/0xdf3bed18e02daeb29e2bbc39c04773578d0fd1c8', 'Optimism', 7),
  ('destino-devconnect-la-sucursal-del-cielo-ethereum-birthday-2025-10y', 'POAP', null, null, 9)
) as v(slug, protocol, nft_url, chain, mints)
join public.events e on e.slug = v.slug
on conflict on constraint event_nfts_unique do nothing;

commit;
